{{- if .Values.secrets.backend }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.backend.BETTER_AUTH_SECRET }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.backend.BETTER_AUTH_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.backend.GEMINI_API_KEY }}
  GEMINI_API_KEY: {{ .Values.secrets.backend.GEMINI_API_KEY | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.backend.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secrets.backend.DATABASE_URL | b64enc | quote }}
  {{- end }}
{{- end }}