apiVersion: v2
name: todo-app
description: Umbrella Helm chart for the Todo Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: todo-frontend
    version: 0.1.0
    repository: "file://../todo-frontend"
  - name: todo-backend
    version: 0.1.0
    repository: "file://../todo-backend"